### ISSUE TITLE
Advanced Company's Portable Terminal

### ISSUE THREAD

**Issue by JubbyDubby** [Drew61854/TerminalGames#10]
Advanced Company's Portable Terminal, when used to purchase any items, doesn't seem to take money from the main terminal, I found that this mod was the cause for it. Cheers

**Comment by Drew61854** [comment]
@JubbyDubby Thank you for bringing this to my attention. Unfortunately fixing that issue would require me to be able to change the Portable Terminal, and I cannot do that because I do not own that mod. Because of this, I cannot fix this issue.
