### ISSUE TITLE
Credits don't save when reloading (again?)

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#11]
Something in the last update broke credits being saved when loading a file. I think this is a reintroduction of an old bug, but I'm not 100% sure it's the same problem, as the former issue claimed credits were 0 at the start of the game, and for me it's 60 until you go to a planet, return to orbit and restart.

**Comment by KKaydoom** [comment]
might be an issue with morecompany or late game store

**Comment by Drew61854** [comment]
@BrawleyGithub @KKaydoom It was indeed my mod, a little oversight to do with how I reset credits when the game is disconnected, not an issue until I changed how I synced credits among players. It's fixed now, but I'm not gonna release a new update just yet. The next patch is going to be the final one, so I'm going to spend a little time stress testing to find any more bugs I can before releasing it. If you find any, please let me know. If not, thanks for finding so many up to this point.
