### ISSUE TITLE
Adventure softlock

### ISSUE THREAD

**Issue by piotrenewicz** [Drew61854/TerminalGames#12]
It is possible to softlock a game of adventure by picking up flashlight arm key device too early.
You don't have any inventory slots available to pickup the last fuse, and there's no way to drop / get rid of any of those items.

I think using a key on a door should consume it. Since unlocking doors does consume keys in the actual game. 
That would be the simplest way to avoid this softlock. 

Also after grabbing / using items, the inspect action still says that those items are present in their room of origin.

Both of those are rather minor issues, do with them what you will.

**Comment by Drew61854** [comment]
The softlock is intentional. You have to be able to lose _somehow_. The other one, no so much. That being said, I'm not working on this project anymore. Thanks anyway!
