### ISSUE TITLE
0 Cash on new save after update

### ISSUE THREAD

**Issue by Sourceshard** [Drew61854/TerminalGames#2]
After the recent update while this addon is activated. Creating a new save and accessing the terminal seems to show/remove all credits from the player. The player is unable to buy any items as they have no money.  Removing/disabling the mod fixes this issue.

**Comment by Drew61854** [comment]
@Sourceshard Thank you so much for bringing this to my attention. I have fixed this issue and will be posting an update soon. Would you like to be credited in the changelog?
