### ISSUE TITLE
Selling scrap does not increase credits on the terminal

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#3]
When you sell scrap at the company desk, you are shown the paycheck screen and your quota fulfilled increases, but the terminal does not gain the credits amount. This was tested in singleplayer (but launched in online mode), I am unable to test multiplayer to determine if it works there. This was verified first in a larger modpack of mine and then with only terminal games (and its dependencies).

**Comment by Drew61854** [comment]
@BrawleyGithub Thank you so much for bringing this to my attention. I will work on this problem shortly and then release an updated version. Would you like to be credited in the change logs?
