### ISSUE TITLE
Dying or getting fired doesn't change credits

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#4]
In singleplayer testing with only Terminalgames and its' dependencies, I didn't lose any credits for dying despite seeing the fines screen. Additionally, I did not get my credits reset to the typical 60 when getting fired.

**Comment by Drew61854** [comment]
@BrawleyGithub Thank you for bringing this to my attention. It has been fixed and the mod has had a new update released. If you discover any more bugs please continue to report them. If you do, maybe one day I can be bug-free. (Probably not)

**Comment by BrawleyGithub** [comment]
I will, and the mod seems to be pretty stable from my experience. I think I found another weird edge case today but I forgot to open that as an issue (and I may have lost the screenshot)
