### ISSUE TITLE
Drawing an ace at 20 busts?

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#5]
Sorry I forgot to post this earlier, but this should be 21. Think this is the one time I have ever busted with an ace, it might check for game over before doing the check to reduce ace to 1 if it's the last card drawn? I'm not sure, this was hours ago while I was trying to find out what was causing the other issue (big modpack, lot of mods to break) so it worked out for me.
![image](https://github.com/Drew61854/TerminalGames/assets/130003223/f0df679a-356f-4c95-9031-8f67c86a8936)

**Comment by Drew61854** [comment]
@BrawleyGithub Thanks for bringing this to my attention. It has been fixed and an update to the mod has been posted. If it keeps up at this pace I'm going to be at version 2.0.25 by the end of the month.
