### ISSUE TITLE
(Hint) Attempting to sue someone creates an exception and stops the game of Hint entirely

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#7]
(Issue 2 of 2) I finally actually tried suing someone in Hint (apparently I am Not Good at solving murder mysteries) and first it didn't enter, then on the second try it went through only to say there was an error processing your request and the terminal basically forgot I was playing Hint at all. I wasn't even sure what the format of "sue" was going to be but everything I tried across a few test games didn't work (sue bracken galley flail, sue bracken, go to location and sue, probably a few others I forget).

[removed log for clearer version below]

**Comment by BrawleyGithub** [comment]
More info: This bug also occurs in a file with only TG. It ALSO only generates the game-stopping exception if you only provide one input (like "sue bracken"). Typing "sue bracken pool flail" doesn't actually do anything. Even with commas. It just sends you back to the choose a room screen. So I don't think Hint is technically winnable at the moment, even without my subpar deduction skills. Would still play for the IRL sanity gain between solo rounds.

**Comment by BrawleyGithub** [comment]
Much smaller output log:
[LogOutput.log](https://github.com/Drew61854/TerminalGames/files/14231831/LogOutput.log)

**Comment by Drew61854** [comment]
@BrawleyGithub 2 for 1 this time, I like it. I have identified the issue in the code and it has been fixed, and an update has been posted. As for how suing works, I have added that when you type 'sue' by itself it will explain how to do it. Funny enough, you could only sue successfully (and lose) when you misspelled the name of the character, and I guess I'm good at misspelling things for it to fly under my radar in testing.
