### ISSUE TITLE
Complication

### ISSUE THREAD

**Issue by CPGSam** [Drew61854/TerminalGames#8]
I assume that the back command is from this mod since when I type it, it says bet canceled. It is interfering with the LateGameUpgrades mod. When I try to buy the back muscles lgu, it says bet canceled. Is there a way to remove the back command in a config file or similar?

**Comment by Drew61854** [comment]
@CPGSam You are correct that the back command is from this mod. Unfortunately there is no way currently to remove certain commands, so your best bet at the moment is to just remove TerminalGames if you want to use LategameUpgrades. I am thinking of overhauling how TG works to move away from using TerminalAPI which would remove most if not all comparability issues, but for now it is not under development.
