### ISSUE TITLE
It was [redacted] with the [redacted] in the [redacted]

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#9]
Uhhhh....
![image](https://github.com/Drew61854/TerminalGames/assets/130003223/d2177658-8428-4dd8-bb63-b74498479351)
This was preceded by my first guess being "flea bar landmine" which returned "nobody had anything!". None of the cards were mine either.

**Comment by Drew61854** [comment]
@BrawleyGithub Hmm. Weird. It doesn't look like your guess was wrong, but rather that the right answers didn't get set right, as suggested by all the [REDACTED]. I've added redundancy to the game's hints being set, hopefully that fixes it. In all my testing I never had this happen, so I hope this is a rare case and you just got unlucky, I was planning on releasing a new update anyway, so this is good timing. It's been updated.
